baseURL = "https://www.pareshmathur.com/"
languageCode = "en-us"
title = "Paresh Mathur"

[params]
description = "Personal website and blog of Paresh Mathur."
author = "Paresh Mathur"
email = "hello@pareshmathur.com"

[taxonomies]
tag = "tags"

[permalinks]
blog = "/blog/:slug/"

[markup]
  [markup.highlight]
  noClasses = false

[caches]
  [caches.images]
    dir = ':cacheDir/images'

[menu]
  [[menu.main]]
  identifier = "home"
  name = "Home"
  url = "/"
  weight = 1

  [[menu.main]]
  identifier = "blog"
  name = "Blog"
  url = "/blog/"
  weight = 2

  [[menu.main]]
  identifier = "resume"
  name = "Resume"
  url = "/resume/"
  weight = 3
